baseURL = "https://aburayaJean.github.io/sql-site/"
languageCode = "pt-BR"
title = "SQL with Jean"
theme = "PaperMod"
defaultContentLanguage = "pt"

[params]
  ShowCodeCopyButtons = true
  defaultTheme = "auto"
  homeInfoParams = { Title = "SQL with Jean 🗄️", Content = "Aprenda SQL do básico ao avançado com exemplos práticos e scripts prontos para baixar." }
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true

[menu]
  [[menu.main]]
    name = "Teoria"
    url = "/teoria/"
    weight = 10
  [[menu.main]]
    name = "Prática"
    url = "/pratica/"
    weight = 20
  [[menu.main]]
    name = "Downloads"
    url = "/downloads/"
    weight = 30
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 40
  [[menu.main]]
    name = "Contato"
    url = "/contato/"
    weight = 50
